# Generated by Django 5.2.16 on 2026-09-29 10:33

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutreDepense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('origin_node', models.CharField(default='', editable=False, max_length=64)),
                ('rev', models.PositiveIntegerField(default=0, editable=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantité')),
                ('montant', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Montant')),
                ('observation', models.CharField(blank=True, max_length=255, verbose_name='Observation')),
            ],
            options={
                'verbose_name': 'Autre dépense',
                'verbose_name_plural': 'Autres dépenses',
                'ordering': ['-date'],
            },
        ),
    ]
