# Generated by Django 5.2.16 on 2026-09-29 10:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PleinCarburant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('origin_node', models.CharField(default='', editable=False, max_length=64)),
                ('rev', models.PositiveIntegerField(default=0, editable=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('litres', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Litres')),
                ('prix_litre', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix / litre')),
                ('montant', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Montant')),
                ('kilometrage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage')),
                ('n_bon', models.CharField(blank=True, max_length=50, verbose_name='N° du bon')),
                ('observation', models.CharField(blank=True, max_length=255, verbose_name='Observation')),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pleins', to='referentiel.chauffeur', verbose_name='Chauffeur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pleins', to='referentiel.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Plein de carburant',
                'verbose_name_plural': 'Pleins de carburant',
                'ordering': ['-date'],
            },
        ),
    ]
