# Generated by Django 5.2.16 on 2026-09-29 10:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrajetPorteChar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('origin_node', models.CharField(default='', editable=False, max_length=64)),
                ('rev', models.PositiveIntegerField(default=0, editable=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('point_depart', models.CharField(max_length=120, verbose_name='Point de départ')),
                ('point_arrivee', models.CharField(max_length=120, verbose_name="Point d'arrivée")),
                ('km_depart', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage départ')),
                ('km_arrivee', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage arrivée')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant payé')),
                ('observation', models.CharField(blank=True, max_length=255, verbose_name='Observation')),
                ('engin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trajets_porte_char', to='referentiel.engin', verbose_name='Engin transporté')),
            ],
            options={
                'verbose_name': 'Trajet porte-char',
                'verbose_name_plural': 'Trajets porte-char',
                'ordering': ['-date'],
            },
        ),
    ]
