# Generated by Django 5.2.16 on 2026-10-03 13:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('origin_node', models.CharField(default='', editable=False, max_length=64)),
                ('rev', models.PositiveIntegerField(default=0, editable=False)),
                ('code', models.CharField(max_length=40, verbose_name='Code')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='Spécification')),
                ('categorie', models.CharField(blank=True, max_length=100, verbose_name='Catégorie')),
                ('stock_initial', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Stock initial')),
                ('seuil_mini', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Seuil minimum')),
                ('observation', models.CharField(blank=True, max_length=255, verbose_name='Observation')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('origin_node', models.CharField(default='', editable=False, max_length=64)),
                ('rev', models.PositiveIntegerField(default=0, editable=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('type', models.CharField(choices=[('E', 'Entrée'), ('S', 'Sortie')], default='S', max_length=1, verbose_name='Type')),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Quantité')),
                ('motif', models.CharField(blank=True, max_length=255, verbose_name='Motif / Bénéficiaire')),
                ('responsable', models.CharField(blank=True, max_length=120, verbose_name='Responsable')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stock.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='stock_mouve_date_69ccce_idx'), models.Index(fields=['type'], name='stock_mouve_type_cedd3e_idx')],
            },
        ),
    ]
