# Generated by Django 5.2.16 on 2026-09-29 10:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteEngin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('origin_node', models.CharField(default='', editable=False, max_length=64)),
                ('rev', models.PositiveIntegerField(default=0, editable=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('nb_chargement', models.PositiveIntegerField(default=0, verbose_name='Nombre de chargements')),
                ('pu_chargement', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='PU / chargement')),
                ('montant_chargement', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Montant chargement')),
                ('qte_carburant', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantité carburant (L)')),
                ('prix_litre', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix / litre')),
                ('montant_carburant', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Montant carburant')),
                ('observation', models.CharField(blank=True, max_length=255, verbose_name='Observation')),
                ('engin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activites', to='referentiel.engin', verbose_name='Engin')),
            ],
            options={
                'verbose_name': "Activité d'engin (Poclain)",
                'verbose_name_plural': "Activités d'engins (Poclain)",
                'ordering': ['-date'],
            },
        ),
    ]
