# Generated by Django 5.2.16 on 2026-10-04 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poclain', '0001_initial'),
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activiteengin',
            name='categorie_roues',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_poclain', to='referentiel.categorieroues', verbose_name='Camions chargés (nb de roues)'),
        ),
    ]
