# Generated by Django 5.2.16 on 2026-10-03 07:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('origin_node', models.CharField(default='', editable=False, max_length=64)),
                ('rev', models.PositiveIntegerField(default=0, editable=False)),
                ('nom_complet', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('matricule', models.CharField(max_length=40, verbose_name='Matricule')),
                ('fonction', models.CharField(blank=True, max_length=100, verbose_name='Fonction')),
                ('service', models.CharField(blank=True, max_length=100, verbose_name='Service / Département')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['service', 'nom_complet'],
            },
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('origin_node', models.CharField(default='', editable=False, max_length=64)),
                ('rev', models.PositiveIntegerField(default=0, editable=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('statut', models.CharField(choices=[('P', 'Présent'), ('A', 'Absent'), ('C', 'Congé'), ('M', 'Mission'), ('R', 'Repos'), ('ML', 'Maladie')], max_length=2, verbose_name='Statut')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='pointage.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='pointage_po_date_a3fd36_idx')],
            },
        ),
    ]
