# Generated by Django 5.2.16 on 2026-10-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='numero_permis',
            field=models.CharField(blank=True, max_length=40, verbose_name='N° de permis'),
        ),
        migrations.AddField(
            model_name='employe',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='statut',
            field=models.CharField(choices=[('P', 'Présent'), ('A', 'Absent'), ('C', 'Congé'), ('M', 'Mission'), ('R', 'Repos'), ('ML', 'Maladie'), ('RT', 'Retard'), ('S', 'Sanction')], max_length=2, verbose_name='Statut'),
        ),
    ]
