# Generated by Django 5.2.16 on 2026-09-29 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('seq', models.BigAutoField(primary_key=True, serialize=False)),
                ('model_label', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.UUIDField(db_index=True)),
                ('payload', models.JSONField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('node', models.CharField(blank=True, max_length=64)),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Changement (journal)',
                'verbose_name_plural': 'Changements (journal)',
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='NodeState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('last_pulled_seq', models.BigIntegerField(default=0)),
                ('last_push_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_ok', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'État de synchronisation',
                'verbose_name_plural': 'État de synchronisation',
            },
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_label', models.CharField(max_length=100)),
                ('object_id', models.UUIDField()),
                ('cote', models.CharField(choices=[('local', 'Local écarté'), ('distant', 'Distant écarté')], max_length=10)),
                ('payload_ecarte', models.JSONField()),
                ('payload_retenu', models.JSONField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Conflit de synchronisation',
                'verbose_name_plural': 'Conflits de synchronisation',
                'ordering': ['-created_at'],
            },
        ),
    ]
