# Generated by Django 5.2.16 on 2026-09-29 10:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieRoues',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('origin_node', models.CharField(default='', editable=False, max_length=64)),
                ('rev', models.PositiveIntegerField(default=0, editable=False)),
                ('libelle', models.CharField(max_length=50, unique=True, verbose_name='Libellé')),
            ],
            options={
                'verbose_name': 'Catégorie de roues',
                'verbose_name_plural': 'Catégories de roues',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('origin_node', models.CharField(default='', editable=False, max_length=64)),
                ('rev', models.PositiveIntegerField(default=0, editable=False)),
                ('nom_prenoms', models.CharField(max_length=120, verbose_name='Prénoms et Noms')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Chauffeur',
                'verbose_name_plural': 'Chauffeurs',
                'ordering': ['nom_prenoms'],
            },
        ),
        migrations.CreateModel(
            name='Engin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('origin_node', models.CharField(default='', editable=False, max_length=64)),
                ('rev', models.PositiveIntegerField(default=0, editable=False)),
                ('nom', models.CharField(max_length=80, verbose_name='Nom / Désignation')),
                ('type_engin', models.CharField(choices=[('poclain', 'Poclain / Chargeur'), ('porte_char', 'Porte-char'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Type')),
                ('actif', models.BooleanField(default=True, verbose_name='En service')),
            ],
            options={
                'verbose_name': 'Engin',
                'verbose_name_plural': 'Engins',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('origin_node', models.CharField(default='', editable=False, max_length=64)),
                ('rev', models.PositiveIntegerField(default=0, editable=False)),
                ('immatriculation', models.CharField(max_length=30, verbose_name='Immatriculation')),
                ('type_vehicule', models.CharField(blank=True, max_length=60, verbose_name='Type')),
                ('actif', models.BooleanField(default=True, verbose_name='En service')),
                ('categorie_roues', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='referentiel.categorieroues', verbose_name='Catégorie de roues')),
                ('chauffeur_actuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='referentiel.chauffeur', verbose_name='Chauffeur attitré')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['immatriculation'],
            },
        ),
    ]
