# Generated by Django 5.2.16 on 2026-10-06 10:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import referentiel.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('origin_node', models.CharField(default='', editable=False, max_length=64)),
                ('rev', models.PositiveIntegerField(default=0, editable=False)),
                ('nom', models.CharField(max_length=60, unique=True, verbose_name='Marque')),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='vehicule',
            name='capacite_tonnes',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, '10 tonnes'), (15, '15 tonnes'), (20, '20 tonnes'), (25, '25 tonnes'), (30, '30 tonnes'), (35, '35 tonnes'), (40, '40 tonnes'), (45, '45 tonnes'), (50, '50 tonnes'), (55, '55 tonnes'), (60, '60 tonnes'), (65, '65 tonnes'), (70, '70 tonnes'), (75, '75 tonnes'), (80, '80 tonnes'), (85, '85 tonnes'), (90, '90 tonnes'), (95, '95 tonnes'), (100, '100 tonnes')], null=True, verbose_name='Capacité'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='numero_chassis',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° de châssis'),
        ),
        migrations.CreateModel(
            name='DocumentVehicule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('origin_node', models.CharField(default='', editable=False, max_length=64)),
                ('rev', models.PositiveIntegerField(default=0, editable=False)),
                ('type_document', models.CharField(choices=[('carte_grise', 'Carte grise'), ('assurance', 'Assurance'), ('visite_technique', 'Visite technique'), ('autorisation_transport', 'Autorisation de transport'), ('vignette', 'Vignette / Taxe'), ('autre', 'Autre')], max_length=30, verbose_name='Type de document')),
                ('numero', models.CharField(blank=True, max_length=60, verbose_name='N° du document')),
                ('date_emission', models.DateField(blank=True, null=True, verbose_name='Date de délivrance')),
                ('date_expiration', models.DateField(blank=True, help_text="Laisser vide si le document n'expire pas (ex. carte grise).", null=True, verbose_name="Date d'expiration")),
                ('fichier', models.FileField(blank=True, max_length=255, upload_to=referentiel.models.chemin_document, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp'])], verbose_name='Fichier (PDF ou photo)')),
                ('observations', models.CharField(blank=True, max_length=200, verbose_name='Observations')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='referentiel.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Document véhicule',
                'verbose_name_plural': 'Documents véhicules',
                'ordering': ['date_expiration', 'type_document'],
            },
        ),
        migrations.AddField(
            model_name='vehicule',
            name='marque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='referentiel.marque', verbose_name='Marque'),
        ),
    ]
