# Generated by Django 5.2.16 on 2026-09-29 10:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('origin_node', models.CharField(default='', editable=False, max_length=64)),
                ('rev', models.PositiveIntegerField(default=0, editable=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('superviseur1', models.CharField(blank=True, max_length=120, verbose_name='Superviseur 1')),
                ('superviseur2', models.CharField(blank=True, max_length=120, verbose_name='Superviseur 2')),
                ('n_bon', models.CharField(blank=True, max_length=50, verbose_name='N° du bon')),
                ('nb_voyage', models.PositiveIntegerField(default=0, verbose_name='Nombre de voyages')),
                ('pu_voyage', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='PU / voyage')),
                ('montant', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Montant')),
                ('km_depart', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage départ')),
                ('km_arrivee', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage arrivée')),
                ('nb_heures', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name="Nombre d'heures")),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voyages', to='referentiel.chauffeur', verbose_name='Chauffeur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voyages', to='referentiel.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Voyage',
                'verbose_name_plural': 'Voyages',
                'ordering': ['-date'],
            },
        ),
    ]
